% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\hypertarget{data-processing-and-summarization}{%
\section{Data Processing and
Summarization}\label{data-processing-and-summarization}}

The NLSY97 is a national longitudinal survey initially performed in
1997. The survey consists of a nationally representative sample of 8,984
men and women born in the years 1980-1984. Following the initial year,
interviews were conducted annually until 2011 and once every two years
after that. The NLSY97 collects extensive information on respondents'
labor market behavior and educational experiences as well as data on
their families and community backgrounds. This will prove a valuable
tool to assess the impact of education and other environmental factors
on the resulting economic factors like income.

Thus, it is worthwhile to examine sex-related differences between
respondents of the NLSY97 and determining if there is a significant
difference in income analyzing sex and other various factors.

To explore the income gap between men and women, a linear regression
modeling income as a linear function of gender was performed. Based on
this model performed on data representing 5089 individuals, men earned,
on average, \$15,923.90 more than females. Furthermore, this income gap
can be concluded to be highly significant based on the p-value of the
model of approximately \ensuremath{4.134829\times 10^{-45}}. This income
gap can be effectively visualized in the box plot below:

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-5-1.pdf}

We can see from the box plot the median values for mean and women's
income. Additionally the top and bottoms of those boxes represent the
1st and 3rd quartiles of the data. Roughly looking at the data, the
median income was approximately greater than or equal to 75\% of women's
income. After determining that the was indeed a significant income gap
between men and women, the next step was to explore what other factors
might contribute to this disparity. We began by investigating our data.

To investigate our data, we constructed a histogram for all of the
variables. These show the number of records that we had for each
variable. For practically all of the variables, there was a large skew
of the data. To account for this, we decided it would be helpful to
convert these variables into categories, so there was a more equal
representation. For example, the variable of days that a child attended
a religious service was approximately 33\% with 0 days, 33\% 1 day, and
the 2-7 days make up the remaining 33\%. So, we converted this to
categories of no days, one day, and multiple days. For other variables,
the split was not as evident, and the skew was shifted. For these
variables, we broke the counts into percentiles, and categorized the
groups based on that. For example, for mothers birth age, we broke the
data into quintiles, and made age range categories for them.

After categorizing our variables, we also inspected them to see if the
data made sense. There was an occurances where the data seemed to be
off, which was the biological mother's birth age. For this variable,
there were many observations of vary young children having children of
their own. To account for this, we replaced any value in this variable
that was under 10 with a NA value. We think the reason this happened was
due to data input errors

\hypertarget{methodology}{%
\section{Methodology}\label{methodology}}

The main approach to analyzing the variables was to minimize the
consequences of human interaction, meaning that the variables that were
chosen were not controlled by the respondent, such as race and gender.
The group decided to not include other variables that are measured by
the respondent's performance such as GPA in order to avoid confounding
variables for income disparities. Additionally, we decided to consider
variables that we only recorded when this survey was originally taken,
in order to eliminate choices made by respondents. With this in mind,
the data analysis method chosen was analysis of variance (ANOVA), as it
would prove valuable to be used for other tests. The group also made use
of t-tests.

It is worth mentioning that the income data has been truncated. For the
ethical purpose of anonymity, the top 2\% of earners' income figures
have been hidden. Instead, the income of a top 2\% earner is set to the
average income of the top 2\%. The fact that the data has been topcoded
will result in slightly higher discrepancies for males, as only 1 in 20
women that belong in an ``elite household'' have incomes to qualify for
a top 2\% earner status. \footnote{Yavorsky JE, Keister LA, Qian Y, Nau
  M. Women in the One Percent: Gender Dynamics in Top Income Positions.
  American Sociological Review. 2019;84(1):54-81.
  \url{doi:10.1177/0003122418820702}} Thus, the displayed results will
undermine the true gender discrepancy across each variable, as it
ignores the large outliers in income, which are data points belonging
mostly to men.

In determining which variables the group would explore further, the
group constructed linear regression models. First, we constructed a
linear regression model that modeled income based on gender alone. Then,
we constructed models that modeled income based on gender and an
interaction with our chosen variables. The intent was to have two
regression models, and perform an ANOVA to determined whether the
interaction of the variable was significant. We decided that a p-value
of less than 0.05 would be the cutoff for determining significance. As
we performed ANOVA test to determine significance, we ran into an issue
with the data frame being of different size. The reason this was the
case was because some values of our variables we missing. In order to
account for this, we created subsets of the data where there were no
missing values in our variables. Then we created a linear regression
based on gender alone, and then another one based on gender and the
interaction between the variable. This allowed us to perform the ANOVA
test.

After running all of the ANOVA tests to determine whether the
interaction was significant, we then explored the variables affect on
the income gap. To do so, we either ran a linear regression or performed
a t-test. Also, since we were comparing different groups, we decided
that it would be appropriate to analyze the percent difference of each
category in our variables, so we would be able to compare them. There
were a couple variables we did not explore further because the ANOVA
test showed that they were not significant, and they can be seen in our
findings below.

One variable that is noteworth that we didn't explore was the urban vs
rural variable. After performing the ANOVA test on the two models, it
was revealed that this was not a siginificant interaction. We thought
that this would be because of different opportunities and cultures that
exist in urban vs rural settings.

\hypertarget{findings}{%
\section{Findings}\label{findings}}

Among the 90 or so selected variables of the data set, the group
selected 10 variables. After performing the aforementioned methods on
the data from the methodology section, the results were as follows:

In order to determine whether any of the additional factors either
exacerbated or mitigated the income gap between men and women, linear
regression models were ran to determine the interaction between gender
and the additional variables. Then, these models were compared to the
linear regression models as a function of only gender using an anova
test to determine whether these factors where significant. The resulting
p-values from these ANOVA tests can be seen in the table below

\begin{longtable}[]{@{}lcc@{}}
\toprule
Factor & P-Value & Significant?\tabularnewline
\midrule
\endhead
current.age & 0.000 & Yes\tabularnewline
race & 0.000 & Yes\tabularnewline
citizen.status & 0.022 & Yes\tabularnewline
household.net.worth & 0.000 & Yes\tabularnewline
days.religious.activity & 0.001 & Yes\tabularnewline
biological.mother.birth.age & 0.000 & Yes\tabularnewline
parents.relationship.child & 0.000 & Yes\tabularnewline
urban.rural & 0.781 & No\tabularnewline
bio.mom.edu & 0.000 & Yes\tabularnewline
bio.dad.edu & 0.000 & Yes\tabularnewline
guard.mom.edu & 0.000 & Yes\tabularnewline
guard.dad.edu & 0.000 & Yes\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{interaction-of-age}{%
\section{Interaction of Age}\label{interaction-of-age}}

Exploring the significance of age on the income gap between men and
women reveals some interesting findings. Below is the table showing the
coefficients of linear regression modeling income as a linear function
of gender interacting with age.

\begin{longtable}[]{@{}llccc@{}}
\toprule
& Estimate & Std. Error & t value &
Pr(\textgreater\textbar t\textbar)\tabularnewline
\midrule
\endhead
(Intercept) & 52929.256 & 21438.355 & 2.469 & 0.014\tabularnewline
sexMale & -95028.953 & 30061.056 & -3.161 & 0.002\tabularnewline
current.age & -303.896 & 558.823 & -0.544 & 0.587\tabularnewline
sexMale:current.age & 2893.822 & 783.541 & 3.693 & 0.000\tabularnewline
\bottomrule
\end{longtable}

As can be seen in the table, the model determined that for females,
every year of age corellated with an decrease in income by \$303.90.
However, the p-value for this correlation was approximately 0.5866,
indicating that this correlation was not significant. On the other hand,
the model determined that for males, every year of age corellated with
an increase in income by \$2,589.92. This correlation was significant,
as indicated by the p-value of approximately
\ensuremath{2\times 10^{-4}}. While the interaction of age was not
significant for females, the graph below illustrates that overall, age
was significant in the income gap between men and women.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-12-1.pdf}

Also, we wanted to explore how the model was fit to the data, so we ran
diagnostic plots as follows

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-13-1.pdf}
\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-13-2.pdf}
\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-13-3.pdf}
\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-13-4.pdf}

After generating plots to evaluate our linear model, we can see our
Residuals vs Fitted plot, the points surround the red line in a fairly
constant manner despite having a gap from about 42,500 to just above
50,000 which may suggest a linear model is inappropriate. The Normal Q-Q
plot is potentially problematic because many of the values don't fit the
line at the extreme ends of the data, especially the high end. This may
cause our p-values to be invalid. The scale location is very similar to
the Residuals vs.~Fitted plot which is concerning and may again suggest
our model is not appropriate. The Residuals vs Leverage plot shows there
are a few points in the data that are outliers (high leverage and
residuals) skewing the model, but not too many. Overall, these charts
suggest modeling income over sex interacted with age in a linear way may
have some drawbacks. Further discrepancies in the correlation of age and
gender may be experienced had the data for the top 2\% of earners not
been truncated, mostly in the male regression line. Considering that
most of the incomes of the top 2\% of earners are going to be older,
male respondents, the regression line may be quite skewed when comparing
age and income, resulting in a higher slope for the male interaction
with age.

\hypertarget{interaction-of-race}{%
\section{Interaction of Race}\label{interaction-of-race}}

To explore the interaction of race on the income gap between men and
women, a t-test was performed on the percent differences within each
racial group. The t-test provided insight into the mean percent
difference, as well as provided a 95\% confidence interval and
determination of whether the difference was significant. The finding
from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
Race & Income Gap (\%) & Upper Bound (\%) & Lower Bound (\%) & P-Value &
Significant?\tabularnewline
\midrule
\endhead
Black & 17.878 & 27.202 & 8.553 & 0.000 & Yes\tabularnewline
Hispanic & 36.704 & 45.115 & 28.293 & 0.000 & Yes\tabularnewline
Mixed Race & 30.096 & 65.202 & -5.009 & 0.091 & No\tabularnewline
Other & 32.640 & 38.512 & 26.767 & 0.000 & Yes\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
17.878\% to 36.704\% more than females in their respective racial
groups. Additionally, it was apparent that the income gap was
significant for all of the racial groups, except Mixed Race. While the
results into the income gap are helpful, visualizing the results allowed
insight to be derived into whether belonging to certain racial group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-16-1.pdf}

From looking at the bar graph, it appears that Black individuals had the
lowest income gap, while Hispanic individuals had the highest income
gap. Thus, we observe that being Black is a mitigating factor to the
income gap, while being Hispanic is an exacerbating factor to the income
gap. Once again, there may be discrepancies in the t-test, as the
topcoded 2\% values may affect the data, especially the ``Other Race''
category. This would result in a higher Income Gap Percentage for the
category, meaning that being another race that is not Hispanic, Black,
or Mixed will contribute to differences in income across genders.

\hypertarget{interaction-of-citizen-status}{%
\section{Interaction of Citizen
Status}\label{interaction-of-citizen-status}}

To explore the interaction of citizen status on the income gap between
men and women, a t-test was performed on the percent differences within
each racial group. The t-test provided insight into the mean percent
difference, as well as provided a 95\% confidence interval and
determination of whether the difference was significant. The finding
from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.31}}\raggedright
Citizenship Status\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.15}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.12}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.31}}\raggedright
Citizen, Born in the U.S.\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.15}}\centering
32.222\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
37.134\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
27.309\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.12}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.31}}\raggedright
Unknown, Birthplace Undetermined\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.15}}\centering
28.511\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
44.520\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
12.502\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.001\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.12}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.31}}\raggedright
Unknown, Not Born in U.S.\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.15}}\centering
35.254\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
63.065\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
7.443\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.013\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.12}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
28.510\% to 35.253\% more than females in their respective citizen
status groups. Additionally, it was apparent that the income gap was
significant for all of the citizen status groups. While the results into
the income gap are helpful, visualizing the results allowed insight to
be derived into whether belonging to certain citizen status group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-19-1.pdf}

From looking at the bar graph, it appears that individuals with an
unknown citizen status, and birthplace undetermined had the lowest
income gap, while individuals with an unknown citizen status, and not
born in the United States had the highest income gap. Thus, we observe
that having unknown citizen status, and birthplace undetermined is a
mitigating factor to the income gap, while having unknown citizen
status, and not being born in the United States is an exacerbating
factor to the income gap. The impact of truncated values of the 2\% may
also impact this t-test confidence interval, though the change would not
be as defined as in the previous interactions, as the question posed in
the survey will result in mostly U.S. citizens. Adding an extra point,
even if it is a big outlier, will not skew the results much.

\hypertarget{interaction-of-household-net-worth}{%
\section{Interaction of Household Net
Worth}\label{interaction-of-household-net-worth}}

To explore the interaction of household net worth on the income gap
between men and women, a t-test was performed on the percent differences
within each racial group. The t-test provided insight into the mean
percent difference, as well as provided a 95\% confidence interval and
determination of whether the difference was significant. The finding
from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
Household Net Worth\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$108,000 to \$159,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
23.988\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
39.138\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
8.838\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.002\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$160,000 to \$289,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
41.182\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
55.286\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
27.079\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$18,000 to \$30,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
26.152\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
42.115\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
10.189\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.001\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$3,000 to \$7,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
28.872\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
43.582\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
14.161\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$31,000 to \$48,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
34.786\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
48.788\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
20.783\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$49,000 to \$72,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
32.929\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
47.916\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
17.942\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$73,000 to \$107,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
43.401\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
59.260\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
27.541\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
\$8,000 to \$17,999\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
33.234\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
47.294\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
19.174\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
Less Than \$3,000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
31.565\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
49.299\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
13.831\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.001\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.23}}\raggedright
Over \$290,000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
17.220\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
33.635\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
0.806\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.10}}\centering
0.040\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
17.220\% to 43.401\% more than females in their respective household
income groups. Additionally, it was apparent that the income gap was
significant for all of the household income groups. While the results
into the income gap are helpful, visualizing the results allowed insight
to be derived into whether belonging to certain household income group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-22-1.pdf}
From looking at the bar graph, it appears that individuals living in a
household with over \$290,000 in annual income had the lowest income
gap, while living in a household earning between \$73,000 and \$107,999
in annual income had the highest income gap. Thus, we observe that
living in a household with over \$290,000 in annual income is a
mitigating factor to the income gap, while living in a household earning
between \$73,000 and \$107,999 in annual income is an exacerbating
factor to the income gap. Surprisingly, the highest income category has
the least contribution to income gap. The top 2\% of income earners are
defined by incomes between \$309,348 and \$737,697. This means that
averaging the incomes of the 2\% and comparing that number will not
reflect the full discrepancy between genders, resulting in a much lower
result, as shown.

\hypertarget{interaction-of-days-religious-activity}{%
\section{Interaction of Days Religious
Activity}\label{interaction-of-days-religious-activity}}

To explore the interaction of days of religious activity on the income
gap between men and women, a t-test was performed on the percent
differences within each racial group. The t-test provided insight into
the mean percent difference, as well as provided a 95\% confidence
interval and determination of whether the difference was significant.
The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.25}}\raggedright
Days Religious Activity\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.25}}\raggedright
Multiple Days\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
28.321\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
38.013\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
18.628\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.25}}\raggedright
No Days\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
23.199\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
32.559\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
13.839\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.25}}\raggedright
One Day\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
25.661\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
35.187\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.18}}\centering
16.135\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.14}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
23.199\% to 28.321\% more than females in their respective religious
activity groups. Additionally, it was apparent that the income gap was
significant for all of the religious activity groups. While the results
into the income gap are helpful, visualizing the results allowed insight
to be derived into whether belonging to certain religious activity group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-25-1.pdf}

From looking at the bar graph, it appears that individuals attending no
religious activity had the lowest income gap, while individuals
attending multiple days of religious activity had the highest income
gap. Thus, we observe that attending no religious activity is a
mitigating factor to the income gap, while attending multiple days of
religious activity is an exacerbating factor to the income gap. Without
a clear connection of high earners and religion, it is indeterminable
how the truncated 2\% data will impact the results.

\hypertarget{interaction-of-biological-mother-birth-age}{%
\section{Interaction of Biological Mother Birth
Age}\label{interaction-of-biological-mother-birth-age}}

To explore the interaction of age of the biological mother during her
first birth on the income gap between men and women, a t-test was
performed on the percent differences within each racial group. The
t-test provided insight into the mean percent difference, as well as
provided a 95\% confidence interval and determination of whether the
difference was significant. The finding from that test can be seen
below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Biological Mother Birth Age\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
19-21\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
30.982\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
39.081\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
22.884\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
22-24\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
31.794\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
40.896\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
22.693\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
24-27\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
37.725\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
48.087\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
27.363\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Over 27\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
24.435\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
36.032\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
12.839\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Under 19\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
34.621\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
45.185\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
24.057\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
24.435\% to 37.725\% more than females in their respective biological
mother's age at first birth groups. Additionally, it was apparent that
the income gap was significant for all of the biological mother's age at
first birth groups. While the results into the income gap are helpful,
visualizing the results allowed insight to be derived into whether
belonging to certain biological mother's age at first birth group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-28-1.pdf}

From looking at the bar graph, it appears that individuals with mother's
who were over 27 when they had their first child had the lowest income
gap, while individuals with mother's who were between 24 and 27 when
they had their first child had the highest income gap. Thus, we observe
that having a mother who was over 27 when they had their first child is
a mitigating factor to the income gap, while having a mother who was
between 24 and 27 when they had their first child is an exacerbating
factor to the income gap. As previously stated, most people in the top
percents of income earners will be men. Thus, excluding the true values
and truncating the data will not skew the impact of a mother's birth
age, as this variable deals with women, not men.

\hypertarget{interaction-of-caretaker-relationship-to-child}{%
\section{Interaction of Caretaker Relationship to
Child}\label{interaction-of-caretaker-relationship-to-child}}

To explore the interaction of the caretaker's relationship to the child
on the income gap between men and women, a t-test was performed on the
percent differences within each racial group. The t-test provided
insight into the mean percent difference, as well as provided a 95\%
confidence interval and determination of whether the difference was
significant. The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Parent Relationship to Child\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Adoptive Parent(s)\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
-0.738\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
48.171\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
-49.647\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.976\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
No\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Anything Else\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
24.339\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
68.016\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
-19.338\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.263\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
No\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Biological Father Only\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
31.326\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
58.197\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
4.455\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.023\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Biological Mother Only\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
27.908\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
36.331\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
19.486\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Both Biological Parents\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
32.250\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
38.139\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
26.360\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Foster Parents\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
-22.319\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
80.078\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
-124.716\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.625\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
No\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
No Parents, Grandparents\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
37.558\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
76.221\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
-1.105\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.057\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
No\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
No Parents, Other Relatives\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
13.049\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
49.176\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
-23.077\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.470\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
No\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Two Parents, Biological Father\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
32.023\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
56.326\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
7.721\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.010\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Two Parents, Biological Mother\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
33.114\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
45.756\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
20.472\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
22.319\% less to 37.558\% more than females in their respective
relationship to caretaker groups. Additionally, it was apparent that the
income gap was significant for the relationship to caretaker groups with
a biological parent, and not significant otherwise. While the results
into the income gap are helpful, visualizing the results allowed insight
to be derived into whether belonging to certain relationship to
caretaker group exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-31-1.pdf}

From looking at the bar graph, it appears that individuals with
biological Mother's only had the lowest income gap, while individuals
with two parents, biological Mother group had the highest income gap.
However, from observing the overall table, it appears that having a
biological parent in the household is an exacerbating factor, while not
having a biological parent in the household is not significant. Once
again, this will be indeterminate, as a top 2\% income may not be
associated with family status.

\hypertarget{interaction-of-biological-mothers-education}{%
\section{Interaction of Biological Mother's
Education}\label{interaction-of-biological-mothers-education}}

To explore the interaction of biological mother's education level on the
income gap between men and women, a t-test was performed on the percent
differences within each racial group. The t-test provided insight into
the mean percent difference, as well as provided a 95\% confidence
interval and determination of whether the difference was significant.
The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Biological Mother's Education\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
21.251\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
31.448\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
11.053\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
40.144\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
46.866\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
33.422\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
No High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
19.401\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
34.742\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
4.060\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.013\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Some College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
35.640\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
44.985\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
26.294\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Some High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
32.521\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
43.218\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
21.823\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
19.401\% less to 40.144\% more than females in their respective
biological Mother's education level groups. additionally, it was
apparent that the income gap was significant for all of the biological
Mother's education level groups. While the results into the income gap
are helpful, visualizing the results allowed insight to be derived into
whether belonging to certain biological Mother's education level group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-34-1.pdf}

From looking at the bar graph, it appears that individuals with
biological mothers with no high school education had the lowest income
gap, while individuals with biological mother's with a high school
education had the highest income gap. Thus, we observe that having a
biological mother with no high school education is a mitigating factor
to the income gap, while having a biological mother with a high school
education is an exacerbating factor to the income gap. However, this
warrants further exploration, and we assume the mitigating factor is
instead a biological mother with a college education. The truncated data
may change the results, but only slightly, as there seems to be a
correlation between the amount of education and the income gap. It is
good to note the ``No High School'' category being the lowest, which
will be analyzed in the Discussion section.

\hypertarget{interaction-of-biological-fathers-education}{%
\section{Interaction of Biological Father's
Education}\label{interaction-of-biological-fathers-education}}

To explore the interaction of biological father education level on the
income gap between men and women, a t-test was performed on the percent
differences within each racial group. The t-test provided insight into
the mean percent difference, as well as provided a 95\% confidence
interval and determination of whether the difference was significant.
The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Biological Fathers's Education\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
28.883\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
39.149\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
18.617\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
30.971\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
38.189\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
23.754\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
No High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
26.466\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
41.378\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
11.555\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.001\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Some College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
36.312\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
46.853\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
25.771\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.30}}\raggedright
Some High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
38.519\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
51.538\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
25.500\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
26.466\% less to 38.519\% more than females in their respective
biological Fother's education level groups. additionally, it was
apparent that the income gap was significant for all of the biological
Father's education level groups. While the results into the income gap
are helpful, visualizing the results allowed insight to be derived into
whether belonging to certain biological Father's education level group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-37-1.pdf}

From looking at the bar graph, it appears that individuals with
biological Fathers with no high school education had the lowest income
gap, while individuals with biological Fathers with some high school
education had the highest income gap. Thus, we observe that having a
biological Father with no high school education is a mitigating factor
to the income gap, while having a Father with some high school education
is an exacerbating factor to the income gap. However, this warrants
further exploration, and we assume the mitigating factor is instead a
Father with a college education. The results are quite similar to the
ones presented in the previous section. Thus, the fact that there is
truncated data may not skew the results significantly.

\hypertarget{interaction-of-caretaker-mothers-education}{%
\section{Interaction of Caretaker Mother's
Education}\label{interaction-of-caretaker-mothers-education}}

To explore the interaction of caretaker father education level on the
income gap between men and women, a t-test was performed on the percent
differences within each racial group. The t-test provided insight into
the mean percent difference, as well as provided a 95\% confidence
interval and determination of whether the difference was significant.
The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Caretaker Mother's Education\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
18.816\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
28.979\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
8.652\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
41.463\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
48.418\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
34.508\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
No High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
19.723\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
35.152\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
4.294\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.012\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Some College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
33.248\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
42.524\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
23.972\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.29}}\raggedright
Some High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
35.635\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
46.794\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
24.476\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0.000\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
19.723\% less to 41.463\% more than females in their respective
caretaker Mother's education level groups. additionally, it was apparent
that the income gap was significant for all of the caretaker Mother's
education level groups. While the results into the income gap are
helpful, visualizing the results allowed insight to be derived into
whether belonging to certain caretaker Mother's education level group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-40-1.pdf}

From looking at the bar graph, it appears that individuals with
caretaker mothers with a college education had the lowest income gap,
while individuals with caretaker mother's with a high school education
had the highest income gap. Thus, we observe that having a caretaker
mother with a college education is a mitigating factor to the income
gap, while having a caretaker mother with a high school education is an
exacerbating factor to the income gap. The data may skew a bit more in
this interaction if the income values were not topcoded due to the
significance of college among guardians, which is also seen in the
guardian/ caretaker father interaction. Nonetheless, the changes in
results will still be trivial.

\hypertarget{interaction-of-guardian-fathers-education}{%
\section{Interaction of Guardian Father's
Education}\label{interaction-of-guardian-fathers-education}}

To explore the interaction of caretaker father education level on the
income gap between men and women, a t-test was performed on the percent
differences within each racial group. The t-test provided insight into
the mean percent difference, as well as provided a 95\% confidence
interval and determination of whether the difference was significant.
The finding from that test can be seen below.

\begin{longtable}[]{@{}lccccl@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Guardian Father's Education\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
Income Gap (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Upper Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
Lower Bound (\%)\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
P-Value\strut
\end{minipage} &
\begin{minipage}[b]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Significant?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
29.245\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
39.863\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
18.628\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
29.309\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
37.573\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
21.044\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
No High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
32.567\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
49.274\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
15.860\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Some College\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
35.157\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
45.826\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
24.487\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.28}}\raggedright
Some High School\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.16}}\centering
43.853\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
60.004\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.17}}\centering
27.703\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.09}}\centering
0\strut
\end{minipage} &
\begin{minipage}[t]{(\columnwidth - 5\tabcolsep) * \real{0.13}}\raggedright
Yes\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

From looking at the results above, males earned, on average, between
29.245\% less to 43.853\% more than females in their respective
caretaker Father's education level groups. additionally, it was apparent
that the income gap was significant for all of the caretaker Father's
education level groups. While the results into the income gap are
helpful, visualizing the results allowed insight to be derived into
whether belonging to certain caretaker Father's education level group
exacerbates or mitigates the income gap.

\includegraphics{Final-Final_files/figure-latex/unnamed-chunk-43-1.pdf}

From looking at the bar graph, it appears that individuals with
caretaker Fathers with a college education had the lowest income gap,
while individuals with caretaker Fathers with some high school education
had the highest income gap. Thus, we observe that having a caretaker
Father with a college education is a mitigating factor to the income
gap, while having a caretaker Father with some high school education is
an exacerbating factor to the income gap. Finally, much like the
previous interaction, the truncated 2\% data will not significantly
alter the results.

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

The findings clearly demonstrate that there is indeed a statistically
significant discrepancy between income across genders. However, some
limitations to this model exist. The first limitation is ignoring the
respondents' grades and drug usage - personal choices rather than
imposed upon them. Furthermore, unidentified confounding variables may
affect the overall interaction between variables, leading to different
t-values and thus different confidence intervals. Finally, the censoring
of top 2\% earner data may skew the results, resulting in further
differences, meaning that the findings of this paper undermine the true
income gap in the United States across gender.

Analyzing the results, some interactions had worthwhile statistics. In
the first variable compared to gender, which was age, the discrepancy
may arise as men tend to stay in jobs, working more hours, and being
more ambitious in their career goals whereas women may be impeded this
progress due to the burden of childcare, though this may not always be
the case. Another interesting variable was the race interaction. The
``Mixed Race'' category was the only non-significant category, but this
may have been due to data issues, as the spread of the variable was
quite large. Further analysis should be conducted on the interaction of
Mixed Race and income. Next was religious activity. It was seen that as
the days of religious activities increased, the income gap did too. This
may happen because of a few reasons; the first reason may be due to time
constraints, as more time spent in religious activities may result in
less worktime, thus leading to a larger gap. Furthermore, families that
engage in increased religious activity may try to uphold ``traditional''
home values, resulting in women choosing activities that deal with
childcare and staying at home while the husband works and earns money
for the family, resulting in a higher income gap. Next, the household
net worth variable showed some unexpected results, with the respondents
with the highest household net worth experiencing the lowest income gap
between gender. This may be because if a respondent inherited money from
a previous family member, the member may choose to not work and sustain
themselves with said money, resulting in a low income for both genders.
Furthermore, if the respondents come from a wealthy family, the
respondents will have access to better resources, which may mitigate the
gender income gap. This explanation may also be applied to the
interactions of income and mother's age at birth, as children of older
women, who will more likely be financially stable, will have access to
valuable resources like schooling that may mitigate the income gap.
Finally, education across the four categories showed a strange result.
High school education was among the categories that resulted in lower
income discrepancy. This may be due to the fact that jobs that only
require a high school education may not be quite high paying.
Furthermore, the gap decreases as the difference of low paying jobs,
such as minimum wage jobs, are not quite big unlike higher paying jobs
that include bonuses, for example. Though the graphs showed some
interesting results, the insights provided by them are quite valuable
and help explain some of the differences in income between gender that
this paper has found.

The overall confidence in this paper's findings is very high. Though the
limited experience of the group members may influence the accuracy of
the model, the conclusions presented by the data are mostly
statistically significant, making the conclusions quite believable and
reputable.

\end{document}
